version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    EKS_CLUSTER_NAME: eks-cluster-last
    APP_IMAGE_NAME: app-tier-image
    WEB_IMAGE_NAME: web-tier-image
    ECR_URI: 047719630685.dkr.ecr.us-east-1.amazonaws.com # Replace with your actual ECR URI like 1234567890.dkr.ecr.us-east-1.amazonaws.com

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing aws-iam-authenticator and kubectl...
      - curl -o kubectl https://s3.amazonaws.com/amazon-eks/1.27.3/2023-09-27/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      ### 1. Build and push APP image
      - echo Building App image...
      - docker build -t $APP_IMAGE_NAME ./app
      - docker tag $APP_IMAGE_NAME:latest $ECR_URI/$APP_IMAGE_NAME:latest
      - docker push $ECR_URI/$APP_IMAGE_NAME:latest

      ### 2. Deploy APP to EKS
      - echo Deploying App to EKS...
      - kubectl apply -f app/deployment.yaml

      ### 3. Wait for LoadBalancer external IP
      - echo Waiting for App LoadBalancer to become available...
      - |
        for i in {1..60}; do
          APP_ELB=$(kubectl get svc user-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [[ "$APP_ELB" != "" ]]; then break; fi
          echo "Waiting for external hostname... ($i/60)"
          sleep 5
        done
      - echo "App ELB: $APP_ELB"

      ### 4. Inject APP ELB into web/nginx.conf
      - echo Updating nginx.conf with App ELB...
      - sed -i "s|__APP_ELB__|$APP_ELB|g" web/nginx.conf

      ### 5. Build and push WEB image
      - echo Building Web image...
      - docker build -t $WEB_IMAGE_NAME ./web
      - docker tag $WEB_IMAGE_NAME:latest $ECR_URI/$WEB_IMAGE_NAME:latest
      - docker push $ECR_URI/$WEB_IMAGE_NAME:latest

  artifacts:
  base-directory: web
  files:
    - web-deployment.yaml
