version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=047719630685
      - REGION=us-east-1
      - APP_REPO_NAME=app-tier-image
      - WEB_REPO_NAME=web-tier-image
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${APP_REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${APP_REPO_NAME}:${IMAGE_TAG}
